import{a as f,S as d,i as n}from"./assets/vendor-dNBuWDsd.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const m="54847700-f9ce1488f27107b1b46500c94",h="https://pixabay.com/api/";function p(i){return f.get(h,{params:{key:m,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data)}const c=document.querySelector(".gallery"),u=document.querySelector(".loader-wrapper"),y=new d(".gallery a");function g(i){let r=i.map(t=>`<li class="gallery-item">
    <a href="${t.largeImageURL}"><img src="${t.webformatURL}" alt="${t.tags}" title=""></a>
    <ul class="info">
    <li class="info-item">likes: ${t.likes}</li>
    <li class="info-item">views: ${t.views}</li>
    <li class="info-item">comments: ${t.comments}</li>
    <li class="info-item">downloads: ${t.downloads}</li>
    </ul>
    
</li>`).join("");c.insertAdjacentHTML("beforeend",r),y.refresh()}function L(){c.innerHTML=""}function w(){u.classList.add("active")}function l(){u.classList.remove("active")}const b=document.querySelector(".form");b.addEventListener("submit",S);function S(i){i.preventDefault();const r=document.querySelector('[name="search-text"]').value;if(r.trim()===""){n.show({message:"You need to type sonething for searching.",color:"red",position:"topRight"});return}L(),w(),p(r).then(t=>{l(),t.hits.length===0?n.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}):g(t.hits)}).catch(t=>{n.show({message:"Something went wrong. Please try again!",color:"red",position:"topRight"}),l()})}
//# sourceMappingURL=index.js.map
